FROM golang:latest
MAINTAINER Jess Frazelle <jess@docker.com>

RUN go get github.com/Sirupsen/logrus && \
    go get github.com/crosbymichael/octokat

ADD . /go/src/github.com/jfrazelle/leeroy
RUN cd /go/src/github.com/jfrazelle/leeroy && go install . ./...
ENV PATH $PATH:/go/bin

EXPOSE 80

ENTRYPOINT ["leeroy"]
