FROM golang:latest
MAINTAINER Jess Frazelle <jess@docker.com>

RUN go get github.com/Sirupsen/logrus && \
    go get github.com/crosbymichael/octokat

COPY . /go/src/github.com/docker/leeroy
RUN go install github.com/docker/leeroy
ENV PATH $PATH:/go/bin

EXPOSE 80

ENTRYPOINT ["leeroy"]
